Registration validation and send POST
krook1024/SZFM_2020_1_KP_B1G pull request #138
Opened 2020-11-26 17:16 UTC by CzinkeM

Nézzétek meg pls hogy jó lesz e így? A validáció tesztelt. A POST requestbe nem vagyok biztos hogy így kell csinálni.

2020-12-04 13:19 UTC, krook1024 commented
@CzinkeM ki lett probalva? Regisztracio utan az adminban megjelenik a tag, megfelelo adatokkal?

2020-12-04 13:20 UTC, krook1024 requested changes

2020-12-04 13:20 UTC, krook1024 commented on client/src/components/client/Registration.js
> +      <Nav.Item variant="primary">
Csak akkor kell megjeleniteni a gombot, ha meg nem lepett be, hasonloan a loginhoz.

2020-12-05 20:24 UTC, fulekylaszlo commented
Az egybeütközést tudod javítani ?

2020-12-06 19:27 UTC, merged