Kovspec szabalyok
krook1024/SZFM_2020_1_KP_B1G pull request #27
Opened 2020-10-09 22:57 UTC by CzinkeM

Nekem nem jutott más eszembe, van meglátásotok?

2020-10-10 16:41 UTC, krook1024 requested changes

2020-10-10 16:41 UTC, krook1024 commented on doc/kovspec.md
> +
ide meg lehetne irni pl GDPRrol

2020-10-10 16:41 UTC, krook1024 commented on doc/kovspec.md
> +A Cookie-kra vonatkozó kormányzati rendelet betartása.
aprosag, de inkabb cookiek-ra vagy megjobb: sutikre

2020-10-11 10:22 UTC, CzinkeM commented
Megcsináltam a kért változtatásokat.

2020-10-11 18:25 UTC, krook1024 approved these changes

2020-10-11 18:26 UTC, merged