Funkspec jelenlegi
krook1024/SZFM_2020_1_KP_B1G pull request #46
Opened 2020-10-12 06:16 UTC by CzinkeM

2020-10-12 08:40 UTC, krook1024 requested changes
hozd be nyugodtan ugyan azt, mint ami a kövspecben van

2020-10-14 09:58 UTC, CzinkeM commented
@krook1024 Lecsekkolod jó-e?

2020-10-14 10:56 UTC, krook1024 approved these changes
igen, pöpec

2020-10-17 06:19 UTC, tocsika7 approved these changes

2020-10-18 19:45 UTC, merged