Rendszerterv Fizikai Környezet
krook1024/SZFM_2020_1_KP_B1G pull request #50
Opened 2020-10-13 09:43 UTC by CzinkeM

Létrehoztam a rendszerterv doksit.
Megcsináltam a fizikai környezet fejezetet, nézzétek már meg mindent jól írtam-e? Illetve a 'Fejlesztő eszközökhöz' mit lehetne írni?

2020-10-13 09:52 UTC, krook1024 requested changes
Pár apróság!

2020-10-13 09:52 UTC, krook1024 commented on rendszerterv.md
> +* laravel
laravelt nem használunk, React (frontend) és Express (backend)-et fogunk használni!

2020-10-13 09:52 UTC, krook1024 commented on rendszerterv.md
> +## Fejlesztő eszközök
jöhetne ide mondjuk pl VSCode mint szövegszerkesztő, Prettier mint formázó eszköz

2020-10-13 09:52 UTC, krook1024 commented on rendszerterv.md
> +* Php
PHP-t nem használunk!

2020-10-13 09:52 UTC, krook1024 commented on rendszerterv.md
> +Az alkalmazás platform független webalkalmazás.
talán ennél említsd meg, hogy a szerver olyan környezetekben fut, ahol nodejs 12.x vagy nagyobb elérhető (linux, windows, ...), a többi jó így, csak legyen külön szedve a felhasználó és a szerver hardverigénye

2020-10-13 10:59 UTC, CzinkeM commented
@krook1024 Megcsináltam a kért módosításokat, le csekkolod?

2020-10-13 12:28 UTC, fulekylaszlo requested changes
Typo: 20.sor - Andorid

Adalék a fejlesztő eszközökhöz, kérlek írd bele az Atom szerkesztőt is.

2020-10-14 09:57 UTC, CzinkeM commented
@fulekylaszlo Megcsináltam a kért változtatásokat

2020-10-14 10:59 UTC, krook1024 requested changes
par dolgot meg eszrevettem, ezeket javitsuk legyszi

2020-10-14 10:59 UTC, krook1024 commented on doc/rendszerterv.md
> +## Karbantartás
ide meg vedd fel legyszi a dependabot altal nyujtott patchek felhasznalasat is!

2020-10-14 10:59 UTC, krook1024 commented on doc/rendszerterv.md
> +A szerver NodeJS 12.x vagy nagyobb elérhető
szerintem ez a mondat felbe maradt

2020-10-14 10:59 UTC, krook1024 commented on doc/rendszerterv.md
> +Támogatott platformok:
ide kene meg egy enter hogy uj bekezdesbe torjon

2020-10-18 20:00 UTC, krook1024 approved these changes

2020-10-18 20:54 UTC, fulekylaszlo approved these changes
Javítva lettek a kért dolgok, így mergelhető.

2020-10-18 20:55 UTC, merged