Created the UserEdit component for the Admin UI.
krook1024/SZFM_2020_1_KP_B1G pull request #77
Opened 2020-10-23 16:13 UTC by tocsika7

2020-10-23 17:18 UTC, krook1024 requested changes

2020-10-23 17:18 UTC, krook1024 commented on admin/src/components/UserEdit.js
> +                <TextInput source='licenseCategory'></TextInput>
a licenseCategory szerintem egy select legyen inkabb -- http://www.opal-autosiskola.hu/kateg.htm

- AM
- A1
- A2
- A
- B1
- B
- B+E
- C1
- C
- C+E
- D1
- D1+E
- D
- D+E

2020-10-24 15:26 UTC, CzinkeM approved these changes
Ok

2020-10-24 17:15 UTC, krook1024 approved these changes

2020-10-24 17:16 UTC, merged