Admin CarCreate
krook1024/SZFM_2020_1_KP_B1G pull request #81
Opened 2020-10-25 18:27 UTC by CzinkeM

Megfelelő lesz így a komponens?

2020-10-27 08:44 UTC, krook1024 requested changes

2020-10-27 08:44 UTC, krook1024 commented on admin/src/components/CarCreate.js
> +export const CarEdit = (props) => (
ezt egy kulon fajlba kellene majd attenni

2020-10-27 11:57 UTC, CzinkeM commented on admin/src/components/CarCreate.js
> +export const CarEdit = (props) => (
Igen, közben rájöttem, meg Laci elkészítette. A többi rendben van?

2020-10-27 16:08 UTC, krook1024 commented on admin/src/components/CarCreate.js
> +export const CarEdit = (props) => (
igen

2020-11-02 10:03 UTC, krook1024 approved these changes

2020-11-02 10:11 UTC, merged